### ISSUE TITLE
[React] Create Initial Temperature Averages for Metadata Section

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#120]
Create a view that computes and displays temperature averages (for the last 24 hours of data) for each probe. Similar to what existed before:

![screen shot 2016-12-19 at 12 17 53 am](https://cloud.githubusercontent.com/assets/6299853/21305436/9db01622-c580-11e6-9f36-556e807ef9fc.png)

**Comment by mlp6** [comment]
Need to remove "bad" data points to avoid skewing these data too much.
