### ISSUE TITLE
[React] Add Potential Graph Configuration Options

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#121]
@aforbis-stokes What parameters would you be interested in configuring on the graph, if any? Was thinking perhaps the sampling rate of the graph (e.g. how many points to show per hour) and perhaps a date range (e.g. last N days) may be interesting. This isn't a high priority feature probably, but just curious! Was thinking about having a little options drawer slide out from the left of the graph for configuration.

**Comment by aforbis-stokes** [comment]
I think options for N days and samples/hr are nice features. Having less points on a 5-7d view makes a lot of sense, but having all data points available for 24hr view is a good alternative. I don't know if it is challenging to build something that is fully customizable by the view in terms of selecting N days or samples/hr. If so, we could create a few options that are controlled, such as a default plot of last 7 days w/ less samples and drop-down menu that allows to select for a 24hr period with all data points. The options for the 24hr period could be each of the last 7 days or the last 24 hr.
