### ISSUE TITLE
[React] Realtime Calculations View 

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#122]
@aforbis-stokes and @mlp6 what, if any, calculations would you (or others) be interested in seeing in real time? Energy supply? Efficiency or volume metrics that represent how well the system is doing perhaps?

**Comment by aforbis-stokes** [comment]
Let me think on this one for a little. I think once I can dive into more post-processing of data after the field systems get back to complete operation (we're testing out part of the functionality last week/this week) that I'll have a better idea of what will be useful.

**Comment by suyashkumar** [comment]
Sounds good! I'll standby on this one then :).

**Comment by mlp6** [comment]
This issue is superseded by #269 .
