### ISSUE TITLE
[Firmware] Only publish BUCKET on change

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#127]
@mlp6 @aforbis-stokes as mentioned in #65, does it make sense to only publish the `BUCKET` event (with the total number of counts) on a change in the bucket count (as opposed to every time we do a `TEMP` publish). This way we'll save cellular data and space in the database by not holding on to redundant publishes. 

Thoughts?

**Comment by mlp6** [comment]
change since last successful publish event

**Comment by suyashkumar** [comment]
whoops this hadn't been updated since the discussion in #65 -- but yes, publishing the change in bucket count since the last successful publish event would be best. This makes us a little less tolerant if we lose data (if the server is off or down--which should not really happen anymore) compared to the old solution, but we will save a ton of publish data and it'll be in a better form!

**Comment by mlp6** [comment]
It appears that the return status of ``publish()`` isn't really a great indicator of actual success (if anything, just that the command was issued, but not truly successful) [https://community.particle.io/t/detecting-if-spark-publish-fails-to-communicate-with-the-cloud/11776/12]  I could try to pull data from the server back to the device to see if it was successful, but that would waste cell data.  For now I'm going to write the code assuming success, but also pass along the timestamp of when it thinks the last successful publish was.  If that timestamp doesn't agree with what the server has recorded, then we can at least know that the latest publish should assumed to be over a shorter time duration and report back no estimate of bucket tips for the missing time.  @suyashkumar @aforbis-stokes sound good?

**Comment by mlp6** [comment]
scratch that... it appears that the latest firmware has better support for this, so I'll setup some condition logic and assume dropped publish events that return ``True`` are rare (for now).

**Comment by mlp6** [comment]
https://docs.particle.io/reference/firmware/photon/#particle-publish-

**Comment by mlp6** [comment]
Bucket tips are now at all sites, so this is an expected published metric.
