### ISSUE TITLE
water levels need to be converted to inches

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#13]
changes should be made to `Pump.h` and `Pump.cpp`

**Comment by mlp6** [comment]
should be done in `LevelSensor.cpp`

**Comment by mlp6** [comment]
I think the correct manual is `docs/Mebcal6 Manual.pdf`.  Can you confirm?

**Comment by aforbis-stokes** [comment]
Mebcal16 is for programming the EchoPod. The EchoPod specs are in the EchoPod manual. P. 5 says the power can be 12-28 VDC. p 19-20 describes the analog output reading

**Comment by mlp6** [comment]
Okay - I'll take a look at your DipTrace schematic to see what resistor you have that current going through.  What range should the level meter be able to read (i.e., at the min and max current values)?

**Comment by aforbis-stokes** [comment]
It is going through a 237Ohm resistor. I believe the current setting on the
sensor is 2" is bottom, everything below that should be 4 mA reading, 12"
is top and 20 mA is the reading at that point. I can change what levels the
4 & 20 mA outputs correspond to via the Mebcal software.

**Comment by mlp6** [comment]
Given that, we can add a simple conversion.  I'll take care of that and push it up, and then I'll let you test, etc.

**Comment by mlp6** [comment]
I have a working version on the `level_inch` branch that you can test.  It converts the levelCurrentmA variable to the output current from the sensor, which I'm guessing you can then convert to inches.

`LEVEL_MIN_MA` and `LEVEL_MAX_MA` are the thresholds, in mA, that you can set for the level thresholds.

Let me know if this works as you would like.

**Comment by aforbis-stokes** [comment]
This looks perfect.
