### ISSUE TITLE
Migrate to discrete components or stick with "stock" controller?

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#131]
Need to figure out if we want to stick, longer-term, with the out-of-the-box controller, or just use a subset of control components integrated on the control board.  Daniel will investigate this after getting the stock controller board working.

**Comment by DanielHull** [comment]
@mlp6 I have a few thought on this issue. The majority of the components on the stock controller are used (https://cdn.sparkfun.com/datasheets/Robotics/EasyDriver_v45.pdf). We could recreate the schematic w/o the voltage regulator and eliminate maybe a square cm of the board though. The following datasheet has good explanations on how we could robustly add this linear stepper to our pcb. (https://cdn.sparkfun.com/datasheets/Robotics/A3967-Datasheet.pdf) Thoughts?

**Comment by mlp6** [comment]
Not sure if that is worth it... how many discrete components would we need to add, and what coding overhead would we introduce if we couldn't "talk" though simple digital write operations?
