### ISSUE TITLE
Decide on pin mapping

### ISSUE THREAD

**Issue by DanielHull** [mlp6/ADPL#142]
investigate if there are any desired considerations for which GPIO pins to assign specifically

**Comment by aforbis-stokes** [comment]
We current use D0,2,and 4 for pump, valve and igniter. Using the other D# pins would be ok. The only concern I can think of would be crowding on the board with more outputs there, but I don't see that being much of an issue. 
All C pins are open except for C4 as well. One consideration I just had, though, is if we ever wanted to use a Photon (maybe only for the lab), that does not have C pins. Don't know if that would be worth considering, but it came to mind.

**Comment by mlp6** [comment]
pin_mappings.h contains all of the current pin usage.  You should be able to use any that are open if you just need digital out.  Only a subset can be used for PWM output if that is needed.

**Comment by DanielHull** [comment]
Yep, I had seen that, just wanted to see if there were additional specs I had overlooked from a wiring and ease standpoint in the physical system. I'll go with the unused D pins!

**Comment by mlp6** [comment]
The only other consideration is that only a subset of pins can be used for interrupts, and if possible, we should keep those free for future event detection.  The interrupt pins have some strange pairings under the hood (i.e., some pins cannot be used as independent interrupts, etc.).
