### ISSUE TITLE
error: ISO C++ forbids in-class initialization of non-const static member

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#15]
It appears that earlier versions of C++ will not allow what the header error message says... so things that compiled fine on my system aren't compiling on Aaron's system, which I'm guessing is using an older version of the C++ compiler.  I'll move these initializations to the constructor.

**Comment by aforbis-stokes** [comment]
Ok, I check for Arduino software updates and downloaded the newest version since last time I check. Code now compiles. 
I now will check with hardware.
