### ISSUE TITLE
Hardware Board Design

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#16]
@aforbis-stokes What is your timeline / when do you leave for your trip to have a board done?  (I will be gone Fri - Wed.)

We have a few options for board design to consider:
- Use perf board to mount all hardware, with wire / solder connections.
- Layout a printed circuit board with DipTrace that we could either etch in-house or send out to be etched.  

Perf board might be totally fine for this since you don't have any surface-mount components.  PCBs would be great if you had to replicate a lot, but you only need 1 for the near future, correct?

**Comment by aforbis-stokes** [comment]
I leave on Sunday morning.

Perfboard is probably good. This is something that I will want to replicate at a later time, but I just need one to take with me (and remaining lab setup) for now.

**Comment by mlp6** [comment]
@sphaerobolus might have some scraps of perfboard looking for a new home that could be donated to this project (and then replaced at some point)... if not, then we should have some in the lab that I can dig up.  Going this route, then you won't need to use DipTrace to route anything.  I would just create a logical layout on the perf board, similar to what you've done on the Breadboard.  We have soldering irons in the lab that you can use to wire it up / test.  We might also have some extra enclosures sitting around; how large of a box might you need to hold all of this?

The last thing is what connectors you want to use to connect the thermistors, etc. to the circuit.  Do you have some terminals in mind?

**Comment by aforbis-stokes** [comment]
I was thinking something like 6"x6" for the box, and for connecting the thermistors to the circuit I thought I would solder them.

However, I think this is something where someone more experienced could probably give a quick look at my set up and recommend something much better than what I have thought of or am aware of.

**Comment by sphaerobolus** [comment]
I do have some perfboard scraps.
