### ISSUE TITLE
compiled memory

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#17]
As it was, compiled code took ~110% of available memory.  Aaron reduced to ~99%, but we need more breathing room for variable space.

**Comment by aforbis-stokes** [comment]
Update on the Arduino/SD card. When I call the setup code for the SD card back in, the rest of the program does not run. I first saw I was not getting information on the serial monitor and thought it was just the print command conflicting, but the output pins no longer work either. 

Looking at the most recent code on GitHub, lines 59-60 (below) are what bring up this issue. Lines 49-55 were other parts that I called back in, but I can have them in without affecting operation.

```
pinMode(10, OUTPUT); //SD card pin
dataFile = SD.open("datalog.txt", FILE_WRITE);
```

**Comment by aforbis-stokes** [comment]
New update on SD card. I have changed some of the coding, and I have a working version. However, if I try to run too much, the serial monitor stops working, and if I include everything, the code gets stuck in the initial loop. I am sending 2 .ino files via email.

"ADPL_tempSD": This file only considers 3 temperature probes (no other hardware/functions). It works exactly how it should.
"ADPL_tempSD": If I increase to 5 temperature probes, the serial monitor no longer works, but the SD card stores data correctly.
"ADPL_complete": Our total working code. Once I bring in the same SD commands as the other file, nothing works correctly. The initial loops begin (ignitor, valve) but stop and restart.

I have tried a couple different Arduinos/SD card shields and external power supply (12VDC) to not rely on the USB cable.

I am at 98% memory with the complete code. Could that be the issue? The ADPL_tempSD is at 75% for 3 probes, 96% for 5 probes.

**Comment by aforbis-stokes** [comment]
Attached files referenced in last Github comment.

**Comment by mlp6** [comment]
I think this could easily be related to how much memory your code is using on the UNO.  Part of the issue is just how much memory that SD card library is consuming.  We could pick it apart to just have the pieces that you need, but not while you are there!  Could you test the unit w/o the serial monitor running (which is using memory) for a while, see that the SD card was written to, and test the function of all of the sensors / pumps / etc.?

**Comment by aforbis-stokes** [comment]
Yes, tried it out this morning with all of the serial commands commented
out. Everything will work with that. Now using 94%.

**Comment by mlp6** [comment]
Great!  Moving forward, we could transition to a different microcontroller w/ a bit more memory to work with if you plan to continue to iterate on this setup.  

Are you happy w/ how it is performing?  Did you ever figure out what was going on with the 5th thermistor?

**Comment by aforbis-stokes** [comment]
That might be a good idea to transition. Marc and I talked with someone
else on the same sanitation grant that uses the raspberry and uploads to a
nice interface they made. We talked about everyone syncing with that for
the Foundation to have easy access.

Happy with this. Way better than my last round as this actually works.

Still haven't figured out that last thermistor. Must be a connection issue,
though I've looked all over and tried redoing them. The breadboard set up I
have works.

**Comment by mlp6** [comment]
Great.  You can easily add a WiFi or similar interface for upload if you have connectivity, unless SD card upload is the envisioned procedure.  We can touch base when you get back (when is that?).

**Comment by aforbis-stokes** [comment]
Yes, I think wifi will be a necessary replacement as we hope to increase
the number of units we have. The SD is good for the few we have for now.

I get back this coming Friday. Will touch back in then.

**Comment by mlp6** [comment]
Moot point since the SD card is no longer being used with the Particle platform.
