### ISSUE TITLE
error in saving to databaseValidationError: Path `loc` is required.

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#179]
Saw that on the server console when I went to restart it with the new device names...

**Comment by suyashkumar** [comment]
Looking at the logs we seem to have received a message from a particle that wasn't in the map (or led to `loc` being undefined for some reason, see below). However particle `520051000351353337353037` is in the map and things seem to be working for now after the restart. Not sure why that happened. Did you perhaps pull without restarting the server? It's possible the map in memory and the map on disk didn't match up for a small window, but I still don't think that would have led to this. 

```
{ coreid: '520051000351353337353037',
  time: 2017-02-15T17:49:29.922Z,
  loc: undefined,
  temps:
   { HXCI: '26.8',
     HXCO: '39.2',
     HTR: '70.9',
     HXHI: '69.8',
     HXHO: '35.4' },
  valveStatus: '1' }
error in saving to databaseValidationError: Path `loc` is required.
```

**Comment by mlp6** [comment]
I think that @aforbis-stokes just changed that device overnight; so probably just a transient issue rearing its head.

**Comment by suyashkumar** [comment]
Yeah, seems like a one off issue, I'll close this out for now.
