### ISSUE TITLE
update part list

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#20]
include power supplies and other misc. electronics hardware

**Comment by aforbis-stokes** [comment]
Power supply:
India - Monitor power supply, Input: AC 100-240V; Output: DC 12V, 6A
Kenya & Philippines - 20W solar panel, Max Output: DC 17.5V, 0.28A with 12V charge controller; connected to 12V rechargeable battery

External hardware:
Valve (all locations) - Powered by same power source as micro-controller; Input: DC 12V, Max 167 mA (Max 2W) http://www.alibaba.com/product-detail/CWX-15Q-series-3-4-SS304_1809778717.html
Pump (India only) -  Powered by same power source as micro-controller; Input: DC 12V, 6 A (48 W) http://www.amazon.com/SeaLand-Sanipump-Discharge-Macerator-Whisper/dp/B000XBH2D4/ref=sr_1_sc_1?ie=UTF8&qid=1422551946&sr=8-1-spell&keywords=seland+waste+discharge+pump
Igniter (all locations) - Powered by AA battery; DC 1.5V, 280-320 mA, Output: 10 kV; http://www.amazon.com/GrillPro-20620-Electric-Button-Igniter/dp/B000FJVKNM

**Comment by mlp6** [comment]
@aforbis-stokes I'm going to close this, but I've started a file based on the above that needs to be more thoroughly completed.  We can/should probably make one of these for each location.
