### ISSUE TITLE
Confirm EEPROM Approach

### ISSUE THREAD

**Issue by DanielHull** [mlp6/ADPL#208]
Needs to ensure that a system reset will not reset the position variable

**Comment by mlp6** [comment]
@DanielHull was this addressed?

**Comment by DanielHull** [comment]
I gave it a try. It was never perfectly implemented, so if you can give it a try that'd be awesome. I'm ordering some particles here shortly so I can play around with the EEPROM firmware some time as well, but it'd be good to do this before Graham and Aaron go off to Kenya
