### ISSUE TITLE
need local SD.h library

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#212]
The make the compilation more robust across a heterogeneous set of compilation computers, we'll want to include the `SD.h` library as part of the repository.

**Comment by mlp6** [comment]
@suyashkumar I remember you had a strong opinion about dependencies on projects.  We need the SD card library for the device, but I don't want the build process to be dependent on having the Arduino IDE installed (that brings along the library).  We could either:
1. Bring in https://github.com/arduino-libraries/SD as a git submodule to make it available, or 
2. Just bring in a snapshot of the relevant src code and header files.

Preference from your perspective?

**Comment by mlp6** [comment]
I am inclined to just plop a copy of the files in a local `libraries` directory in this repo; git submodules (or subtree) can create headaches for folks.

**Comment by suyashkumar** [comment]
Sure, go ahead and plop a copy of the files in a libraries folder. 

We may consider using an embedded build system like [platformio](http://platformio.org/) one day to elegantly handle dependency management...but for now they don't really support the Particle boards.

**Comment by suyashkumar** [comment]
If we're going to do this instead of a submodule, we should keep track of the commit hash that we snapshotted and put in our repo.
