### ISSUE TITLE
Investigate usage of on-board RTC chip

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#239]
write UTC time to the SD card file

**Comment by mlp6** [comment]
outdated example syntax: https://github.com/bkobkobko/SparkCoreLibraries

**Comment by mlp6** [comment]
It looks like the Electron has an on-board RTC... will use `Time.now()` to get UTC to write to the SD card.  Need to look into powering `VBAT` on the board to have the time persist across power cycles.  Maybe use a rechargeable that can be kept at voltage with the solar power... or a long-term coin cell.

**Comment by mlp6** [comment]
@aforbis-stokes is there power going to the SD card (`VBAT` pin) board to maintain time on it?

**Comment by aforbis-stokes** [comment]
Yes, SD is always powered by Electron

**Comment by mlp6** [comment]
We'll need to test if the RTC maintains time after power cycles.  Something else for Graham to test once we figure out why the timestamps aren't being written (issue #253)
