### ISSUE TITLE
[frontend] flow data graph

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#242]

**Comment by aforbis-stokes** [comment]
Reporting flow is most valuable. Flow[L/hr] =#tips*0.325[L/tip] / ((Current_time-Previous_time[min])*1/60[hr/min])
The 0.325 is average amount of fluid required for a tip. Each location varies slightly (+/-2%), but we can correct for our own post-processing later. This value is close enough for front-end visualization.
