### ISSUE TITLE
selectively include SD card library

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#246]
We need to investigate the compilation error when we don't need the SD card... right now it is globally included on devices that don't have an SD card, which almost doubles our current firmware size... no bueno for OTA flashes.

**Comment by CalNightingale** [comment]
To my knowledge, with `#include` statements it is impossible to selectively include the library short of commenting out the include line and recompiling (however, this will cause errors with all other SD-related functions, ex. SD publish functions)
