### ISSUE TITLE
Add Exhaust temp into published data string

### ISSUE THREAD

**Issue by aforbis-stokes** [mlp6/ADPL#267]
Exhaust temp data will be used for data analysis. Should not be displayed on webpage (will look cluttered). Include in data publishes.

**Comment by aforbis-stokes** [comment]
Bumping this issue back towards the top. We have some burner enhancements coming up and having access to the exhaust temperatures before and after the burner change will be useful.

**Comment by aforbis-stokes** [comment]
Getting this Exhaust temp probe in the published data string is now a pretty critical update. When could we roll this out? @Graham-H-Miller did his own edit to some code to get the Exhaust probe read locally, but we need to be able to access it through a data pull. We can see the data stream in the Particle Console, so the hardware functionality with Graham's local software edit is working correctly.

**Comment by mlp6** [comment]
@aforbis-stokes do you expect the `Exhaust` temperature to be available for all of the devices, or just some?  Our logic for publishing / saving data only handles the bucket tip as an optional item.  If we want exhaust to be optional too, then we need to rework that... but if we can just let it publish data you won't use and don't worry about the wasted bytes, then we'll let it go.

**Comment by aforbis-stokes** [comment]
I do not see any harm in always publishing the exhaust temp. I imagine there may always be something we can pull out of that. At the same time, we do use the bucket tip everywhere, all the time. Could switch the bucket tip to a variable that always publishes and the exhaust to an optional, as long as that does not conflict with how the bucket tip is written in. Either way, I'm good with whatever is easiest.

**Comment by mlp6** [comment]
If the bucket tip is used everywhere now, then I think that we should simplify the code with the same publish/save string for all variables, all the time.

@suyashkumar can you confirm that your server-side string parser uses the variable name to parse the value and **not** the order of the variables being published?

**Comment by mlp6** [comment]
issue #290 removed the optional `no_bucket` data string from being published/saved

need to confirm that 69 characters can still capture all of the new information being sent on the cell publish, and 79 characters is enough for the SD card save

**Comment by mlp6** [comment]
@Graham-H-Miller can you confirm with the latest code, which you'll need to re-download here (https://github.com/mlp6/ADPL/archive/v2.6.0-alpha.1.zip), that the publish string for the cell isn't getting clipped?
