### ISSUE TITLE
Pump / Ignitor Timer Conflicts

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#3]
Running the pump and ignitor on separate timers that will not conflict has been challenging.

**Comment by mlp6** [comment]
This problem should be resolved by the independent power circuits with digital out pin control for each.

**Comment by mlp6** [comment]
@aforbis-stokes do you have any details on the errors that you are getting when you try to get both of these timers working?

**Comment by aforbis-stokes** [comment]
This is probably just a weakness of mine in coding, but when I try to have the pump run for a certain amount of time, everything else waits for that to complete. Same with the ignitor turning on, everything else waits for that to complete.

**Comment by mlp6** [comment]
Okay - we should be able to deal with that.  Is `ADPL_complete.ino` your latest working version (i.e., I shouldn't look at `ADPL_labsetup.ino`)?

**Comment by aforbis-stokes** [comment]
Correct, ADPL_complete is the latest.

**Comment by mlp6** [comment]
I will take a look at it now... keep an out out for some commits, etc.  I do _not_ have an Arduino with me right now, so I won't be able to test for bugs that I might introduce in syntax, etc.

**Comment by mlp6** [comment]
I found a few areas of the code that we can really streamline, which I will tackle right now.  Question - line 85 of `ADPL_complete.ino` has a `delay()` call in the loop, but none of the other loops do; is that for a reason, or do you just need a general delay between readings?

My first optimization will be to consolidate your temp probe readings a lot to be more readable and modular, but I want to check about that `delay()` quickly.

**Comment by aforbis-stokes** [comment]
That comes from the example code in the Thermistor guide document. It had a delay between the readings that I assumed did not need to happen between reading each probe but needed to happen somewhere in the loop.

**Comment by mlp6** [comment]
~60% done; have a meeting now, but will get back to this ~1 PM.

**Comment by mlp6** [comment]
The issue w/ the conflicts in the activation of the ignitor or pump delaying subsequent execution is related to the use of serial `delay()` commands that will pause `loop()` until the specified delay has elapsed, which is _not_ the desired function.  Instead, we need to activate these components and continue to loop and check when to turn them off, rather than delay things.  I will implement this on the `ignitor` branch, and will then do the same for the pump.

**Comment by mlp6** [comment]
@aforbis-stokes Is it true that everytime you use the ignitor that the following steps occur:
1. Turn on the ignitor
2. Hold it on for 5 sec
3. Turn off the ignitor

Do you ever not activate the ignitor that way?

**Comment by aforbis-stokes** [comment]
Correct. Off for 15 min before turning on again.

It should also only be on when the valve is open (T<72)

**Comment by mlp6** [comment]
Okay - doing lots of code consolidation then, and hopefully making all of it more modular and readable for long-term maintenance.  I'm on a conference call now, but concurrently coding.  Hoping to get you something to test soon.

**Comment by mlp6** [comment]
@aforbis-stokes Can you inspect lines 98-123 for the code in the `ignitor` branch to see if my logic for the valve / ignitor make sense?  You can choose what branch you are on from the GitHub repository webpage if you don't have it on your local computer.  I don't want to break the `master` branch with non-functioning code (yet).   I replaced some of the loop code with functions that "do" what you want (at the end of the file).

**Comment by aforbis-stokes** [comment]
Yes, I follow the logic. Seems a little more simple than what I was trying to do.

**Comment by mlp6** [comment]
Great... now onto the pump.  Then you'll be on the hook the test everything.  :)

**Comment by mlp6** [comment]
@aforbis-stokes For the water level, if you are at an intermediate level, and you have turned on the pump for 5 min, do you want to impose the 55 min off time even if the level goes above your max threshold or only impose the 55 min off time if the level remains in the intermediate state?

Would it be bad to just keep the pump on until at the min level and give it some hysteresis so it doesn't keep turning on and off right around that threshold?

**Comment by aforbis-stokes** [comment]
For the first, I was assuming the level would not change that quickly, so I was ok with the pump being off 55 minutes, but if it's a simple change to come on if it does reach that threshhold, then that would be a good fix.

Second, are you saying pump on until min instead of a timer? I don't think that would work so well, but some hysteresis around the thresshold would be good. 

What I am hoping is to get the pump to operate so that the flow into the system is the same throughout the day (5 min every hour) while the level would rise during high use periods and drop over night, but trying to stay between the min and max.
