### ISSUE TITLE
request temperature data on demand

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#30]
In addition to the electron publishing data, add the ability to poll the device for temperatures on demand.  I'm guessing this will require `Spark.variable()` declarations for all variables that will be polled.  

Hopefully these can be added in the data stream of things also being published, but maybe not all of the thermistors... or maybe you can choose which ones.  

I'm not sure how much data the request will add on top of the data sent back.

**Comment by suyashkumar** [comment]
Fantastic--indeed we'll use `Particle.variable()` to expose the necessary variables using HTTP GET requests. I've looked over the codebase and I suggest we just do the variable registration in the TempProbe constructor:
`Particle.variable("temp"+String(_pin), temp);` 

I can go ahead and make this change and submit a pull request for you to review. If I make the change in the local code, will you or someone upload it to the Particle Build setup, or should I make the changes in that environment? Just let me know!

**Comment by suyashkumar** [comment]
Also, what sort of testing (if any) do we do before making live updates? Any thought to testing with a wifi photon?

**Comment by mlp6** [comment]
I have been making all of the changes in my local working copy of the code, and then just cut-n-paste into the web IDE so that Aaron in Kenya can push.  The only "testing" that is done is that it compiles.  We had a WiFi Photon going, but I've just been relying on the "verify" to make sure the code is at least valid.
