### ISSUE TITLE
Ignore Negative Probe Values

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#32]
Ignore negative values when plotting (in front end). @aforbis-stokes

**Comment by mlp6** [comment]
Maybe instead of ignoring them, they can (should?) be indicated on the plot (like a red X on the x-axis at that time point) in case that would be useful for @aforbis-stokes would like to know when it has been disconnected / damaged.

**Comment by aforbis-stokes** [comment]
@mlp6 I like that idea.

**Comment by suyashkumar** [comment]
Agreed--if this is where we want to see that sort of outage data that makes a lot of sense!

On Apr 19, 2016, at 10:00 AM, aforbis-stokes <notifications@github.com<mailto:notifications@github.com>> wrote:

@mlp6https://github.com/mlp6 I like that idea.

##

**Comment by suyashkumar** [comment]
Sup y'all--I think let's talk in person about how to handle these (disconnects vs. bad values). Would something like an error log make sense?
