### ISSUE TITLE
How much data to plot

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#38]
With the current settings we're essentially pulling down and plotting the _entire_ database at once. Is this what we want to be doing? Are we most interested in plotting the last _N_ days in the dashboard? @aforbis-stokes

**Comment by aforbis-stokes** [comment]
Good point. Since all of the data will be available for download, the dashboard does not need to show everything from the beginning. How about showing the last 14 days?

**Comment by suyashkumar** [comment]
Last 14 days sounds good--instead of doing that exactly I'll just send over the last 9000 data points which should be >=14 days of data.
