### ISSUE TITLE
Other Dashboard Data

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#39]
What other "at-a-glance" type of data would be good to show in the dashboard? Maybe the avg temps over the last hour for each probe? 

@aforbis-stokes 
@mlp6

**Comment by aforbis-stokes** [comment]
The average temp is a good idea. Another is if the Valve is on

**Comment by suyashkumar** [comment]
Sweet, should we publish valve status along with our other temp data packages? We can likely also expose this using spark.Variable()

**Comment by mlp6** [comment]
Need to add some sort of plot for the bucket tip (count and timestamps of tip); maybe in a separate plot next to the temp plot.

**Comment by aforbis-stokes** [comment]
How about a second y-axis for bucket tip? Could be on the right, and would not require much labeling so shouldn't make things look too cluttered. 
We have 3 buckets, and each has a slightly different volume/tip, so I don't think incorporating that into the code works very well. But, if we converted for the web display, it would be more relevant for whoever is looking. Each tip =325 mL of waste, so the y-axis could be 0 to 325 mL.
Flow affects the temperature, so having the tips matched up on the same time axis as temperature would be interesting to see.

**Comment by mlp6** [comment]
This has been integrated into current functionality, so going to close for now.
