### ISSUE TITLE
create GPIO pin-mapping 

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#45]
need to map pins to function in a way that is robust for slight variations in different deployments.  would like to have the function names be universal, and the actual pins be what can change, especially since a blown pin in the field could trigger and on-the-fly redirect to a new pin

**Comment by mlp6** [comment]
commit cfe344e adds this to the code; need to make accessible to the web server

**Comment by mlp6** [comment]
need to figure out how this mapping changes for the Photon (vs the default Electron), and how different deploys based on location that use more temp probes, etc. would change

**Comment by suyashkumar** [comment]
@mlp6: what do you need to make accessible to the webserver? Let me know how I can help if needed
