### ISSUE TITLE
worth knowing level sensor readings?

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#47]
@aforbis-stokes would it be valuable to trace the water level when we also track the temps?

**Comment by aforbis-stokes** [comment]
We are actually starting to move away from the level sensor. That is only used in India and is a special case scenario. There have been some treatment system layout changes, and the level sensor is not being used at the moment (though still installed in case we change back). I don't have a clear plan for the level sensor, so I think we can put that off for now.
