### ISSUE TITLE
get BJTs and relays from Matt; breadboard too

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#5]

**Comment by mlp6** [comment]
These are working.  Need to replenish Matt's supply.

**Comment by mlp6** [comment]
@aforbis-stokes We need to replenish Matt's components... do you have a source where we can order these for your replication needs, etc.?

**Comment by aforbis-stokes** [comment]
I have only used Radioshack and Amazon to buy components. I have a PO code for our grant so can order more on my own or provide that code.

**Comment by aforbis-stokes** [comment]
I have done more hardware checks. I found 3 relays that go up to 14 VDC at Radioshack to replace the other relays. While checking these, I found that 2 of the 3 BJTs no longer work. Are there more of these available that I can continue tests with? I figure once I have everything completely running for a longer test, I will buy duplicates and replenish Matt's supply.
Also, what do we need to do to fabricate a board?

**Comment by sphaerobolus** [comment]
I could provide some more BJTs. I'm in the Teer basement, the '0' level. I'll be here today until about 4:00.

**Comment by aforbis-stokes** [comment]
@sphaerobolus I picked up some 12VDC relays that are similar to the 5VDC ones you supplied. They do not have the 87a prong (Normally closed), and one of my components needs to switch between normally open/normally closed. Do you have any relays around that can operate under 12VDC have both connections?

**Comment by sphaerobolus** [comment]
@aforbis-stokes I think I can supply that. Stop by when you get a chance. Also, bring one of your relays--I'd like to confirm the missing NC pin. That a relay is missing said pin surprises me.
