### ISSUE TITLE
authbind node server.js

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#51]

**Comment by mlp6** [comment]
@suyashkumar it appears that if the VM server goes down that someone needs to login and manually restart the server.  Is there a downside to triggering this automatically on boot?

**Comment by suyashkumar** [comment]
Nope, there is no downside to doing this--we should definitely do this! If you'd like me to take care of it just assign me an issue and I'll do it!

**Comment by mlp6** [comment]
For my knowledge, does Ubuntu utilize an `etc/rc.local` approach to startup scripts, or is another method preferred?  (Obviously, I'm much more of a Redhat person than Debian...)

**Comment by sphaerobolus** [comment]
The ubuntu machines that drive the dept 3D printers use the rc.local approach to startups.

**Comment by mlp6** [comment]
issue bdf896c
