### ISSUE TITLE
Downsample data for plotting

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#53]
Plotting 8000 points can cause some performance issues on the front end, and it seems we dont really need to plot at the resolution that we do. Is there some merit to simply downsampling the data we are plotting by, say, a factor of 2? 
@aforbis-stokes

**Comment by aforbis-stokes** [comment]
I'm not so familiar with "downsampling." Is this simply plotting 1/2 the data that we have? As long as it does not affect the total hard data that can be accessed in the raw csv file, I trust your judgment in what makes the rest easier/better to process and display.

**Comment by mlp6** [comment]
I think this is done with the downsampling factor of 100 that is in the plot component, so I'm closing this.
