### ISSUE TITLE
Dashboard Metadata Display

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#54]
Display metadata on the front end like:
- Avg Temp over past N minutes for each channel
- Number of bucket tips in the last H hours (perhaps H=24?)
-  ??
  @aforbis-stokes can you add to this as needed?

**Comment by aforbis-stokes** [comment]
Let's do:
- Avg temp over past **60 minutes**
- # bucket tips in last **24 hours**
- Current Valve status

**Comment by suyashkumar** [comment]
New API routes will need to be build out for bucket tips, going to make a new issue for building bucket tip infrastructure. See #65.
