### ISSUE TITLE
Push Updates for Front End

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#55]
Push updates using socketio of the data displayed in the front end as updates to data arrive (e.g. other bucket tips and new temp data)

**Comment by mlp6** [comment]
I was just thinking about this being a great feature... right now I'm reverting to reloading the entire page and selecting the correct device, etc.  FYI, 3 devices are online now (2 in Kenya for testing)

**Comment by suyashkumar** [comment]
Just implemented this. However, this will be the most stable when we receive all data on the server at once. Right now it triggers an auto refresh once the server and frontend see that an `HXHO` packet is recieved (which is usually at the end of the series).
