### ISSUE TITLE
HXHO Publish Sometimes dropped?

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#56]
Looks like the HXHO publish sometimes gets dropped--only on occasion. Might this be because it's the fifth in a series that only allows a burst of 4 in one second? Note 4 seconds are needed after a burst of 4...
@mlp6 thoughts?
From the Particle Docs:

> Currently, a device can publish at rate of about 1 event/sec, with bursts of up to 4 allowed in 1 second. Back to back burst of 4 messages will take 4 seconds to recover.

**Comment by mlp6** [comment]
Sounds like a great catalyst to publish all of the temperatures at once (issue #29)... but it also sounds like this will break the server backend that has to parse this out.  I'm going to break this out into a feature branch to test on the local Duke electron (when the new one comes in) before pushing this to Kenya.
