### ISSUE TITLE
gasOn Reporting Oddly

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#57]
Looks like getting the gasOn boolean using the ondemand infrastructure gives us an odd number. In the response below, it's returning `988209275` from ADPLKenyaNorth0437. From the lab electron it was returning `true` as expected. Might this have to do with firmware changes? 0.5.0 on the lab electron and 0.4.8 on the KenyaNorth. Always thought a bool was just the same as an int (all one byte storage in memory set to either a 1 or 0, but perhaps with this firmware that is not the case). Note that this number can't be stored in a byte of storage.

Will investigate. Thoughts @mlp6 ?

``````
{
  "cmd": "VarReturn",
  "name": "gasOn",
  "result": 988209275,
  "coreInfo": {
    "last_app": "",
    "last_heard": "2016-05-21T05:23:27.979Z",
    "connected": true,
    "last_handshake_at": "2016-05-20T21:44:09.224Z",
    "deviceID": "1b0048000c51343334363138",
    "product_id": 10
  }
}```
``````

**Comment by mlp6** [comment]
I was able to update the system firmware to 0.5.0 OTA for ADPLKenyaCentral9822.  ADPLKenyaNorth0437 timed out during the same operations, so that is still running 0.4.8.

**Comment by mlp6** [comment]
Just got `gasOn` from ADPLKenyaCentral9822 and received a `true`.

**Comment by mlp6** [comment]
I think this has also been fixed, so going to close.
