### ISSUE TITLE
time loop()

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#61]
need to determine how fast loop() is executing (when not publishing)

**Comment by mlp6** [comment]
@oo22 do you think you could benchmark `loop()` execution time?

**Comment by mlp6** [comment]
On first benchmark, it is taking ~5.25 s to complete each loop, which is **way** longer than I expected.

There are two courses of action:
1. Identify the bottleneck and reduce that.
2. Make the bucket tip come in via an interrupt event.

I am leaning towards option 2.

**Comment by mlp6** [comment]
The bottleneck is the thermistor reads, which take 1 s each, and there are 5 of them serially, which take 5 s of each loop.

I am leaning toward implementing solution that get at both options 1 and 2 above:
1. Rotate between each of the 5 thermocouples with each loop, so that the loop execution time is closer to 1.25 s, but each thermocouple updates only once every ~5 s (not really an issue)
2. Associate the bucket tip with an interrupt event.

@aforbis-stokes is there any problem with changing the input pin for the bucket tip counting?  Not all pins support interrupts.

**Comment by aforbis-stokes** [comment]
@mlp6 I see no problem with these steps; I will try out the bucket this morning. Changing the input pin is no problem.
