### ISSUE TITLE
Push Notifications Broken

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#64]
Push update isn't working

**Comment by suyashkumar** [comment]
It's because socketio is pointing to localhost:9000 even on production. Will default this value to pulse.suyash.io but this needs to be changed for local testing. Maybe this can be set by templating in the future.

**Comment by suyashkumar** [comment]
Server side error, because data.name is undefined

**Comment by suyashkumar** [comment]
Closed by changing data.name --> data.coreid (there was a change at some point)

**Comment by suyashkumar** [comment]
Whoops it's data.probeid

**Comment by mlp6** [comment]
I think this broken when I switched to a single temp publish event (which appears to be working!).  Javascript and I are still not on the friendliest of terms, but we're making it work.
