### ISSUE TITLE
Bucket Tip Infrastructure 

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#65]
With the addition of bucket tip publishes, new API routes need to built along with the bucket tip dashboard item (number of bucket tips in the last 24hrs). 
@aforbis-stokes: What sort of information about the bucket tips is usually needed? The number in the last 24 hours, the last global count to date, and perhaps a historical record of when all bucket tips have happened? Just curious!

**Comment by aforbis-stokes** [comment]
@suyashkumar sorry for delay, was home visiting family. The number in last 24 hours would be good for dashboard. A record of tips with time of tip is important for us to evaluate operation. Plotting tips with time would be a nice feature and could possibly be overlaid with temperature.

**Comment by suyashkumar** [comment]
@a.forbis.stokes

**Comment by aforbis-stokes** [comment]
On Particle Console: Each 2.5 data reporting I receive a cumulative number of tips from the start of the Particle turning on. @mlp6 have talked a bit on how to handle as that number will max out at some point. 
The way that I worked the tipping bucket & counter separate from the Particle was to report a total number of tips for one day (~100 tips/day). Knowing the time of tips is very helpful because from that I can get a flow profile for the day.
Moving forward: Resetting tip count at midnight each day would help data handling. The current method of reporting cumulative tips is probably ok. I can at least track tips w/in a 2.5 min window over the 24 hr period, which is pretty good. On the web page meta-data, number of tips that day is a good indicator. And that count just be an updated value directly from the Particle data reporting. Putting tips on the graph would be great but a little trickier. I'll see if I can think of simple way that gets the idea across well.

**Comment by aforbis-stokes** [comment]
Thoughts on working with tipping bucket on web server displays. I used the Kenya csv to get the temp data and made up tip data. 
![image](https://cloud.githubusercontent.com/assets/10760289/20763809/a4183be2-b6f9-11e6-8ddf-3d36140601e8.png)

**Comment by suyashkumar** [comment]
@aforbis-stokes sweet thanks! Couple thoughts:

Storing bucket tip events along with a time stamp will be very easy to do (and I can do cumulative counts on my own given the timestamps, in addition to holding onto the actual count the device sends). 

Would the cumulative tip count reset every day in the graph you propose?

It seems to me it __might__ make sense to create a separate view (perhaps tabbed?) to display more in depth bucket tip data. What features are important to you in a flow profile (particularly in an at-a-glance profile)? Does a histogram (hour bins?) of bucket counts in a given day (maybe togglable to over multiple days) make sense? Are we perhaps interested in seeing how a given day's profile might deviate from the typical average or expected profile? Are we trying to draw comparisons between profiles sites/units?

Not sure how much of this type of analysis should be done in post processing vs what would be helpful in an at-a-glance live view. 

@mlp6: as we start to grow the complexity and feature set here I'm drawn back to the idea of overhauling at least the front end to react to enable scalable growth using what I think is a more understandable and modular paradigm compared to angular...

**Comment by aforbis-stokes** [comment]
@suyashkumar that sounds good to me!

Yes, I would have the cumulative tip count reset each day (in meta-data and raw data on csv). 
@mlp6 would that be done on the Particle's software?

Re: the figure, what I was meaning to put across was cumulative tip count is great for the meta-data, and I assume that cumulative tips with time on the figure would be the easiest to implement. That figure (top in my example) would have value, but the more valuable figure is the second in the example that shows individual tips w/ time stamps to give a view of what the flow pattern looks like. I figured it would take a couple extra steps to generate. If that is simple, then that is what I would recommend.

At a glance, what I would find most useful is a flow pattern. The details of the flow pattern are less important the image of seeing how intensity of flow impacts temperature. I can get all of the details in post-processing.

This picture below is our anticipated flow pattern. An output figure similar to this is what I want in the end, which is ok if it's through post-processing.

![image](https://cloud.githubusercontent.com/assets/10760289/20842238/ebde8fd0-b884-11e6-8b70-e5643e1d6010.png)

**Comment by suyashkumar** [comment]
@aforbis-stokes 
We now have bucket tips being recorded in the database (since #125) but the initial results show that the number being reported is not changing over the course of at least this past day ( check out http://adpl.suyash.io/api/bucket/list/ADPLKenyaN3763 ). You mentioned that time of tip is very important -- we shall get that within 2.5 mins as it seems the current firmware setup is to publish a `BUCKET` event __every time__ we publish a `TEMP` event. 

@mlp6, @aforbis-stokes I think it might only make sense to do the BUCKET publish if the value has actually changed since the last publish (assuming that we know the publish happened successfully, which it seems is the case). This will save us data in the database and more importantly will save us cellular data (no need to send redundant data) :)

**Comment by aforbis-stokes** [comment]
No tips are coming through right now because I have taken the timerblox one-shot out while we test the valve/igniter in the field (that piece is the first to get damaged if something goes wrong).

For the most part the gas valve will open when there is flow (bucket tip), but that may not always be the case.

**Comment by suyashkumar** [comment]
@aforbis-stokes ah, that makes a lot of sense--those timer chips can be pretty sensitive.

What're your thoughts on doing the bucket-tip publish when the event happens as opposed to every 2.5 mins?

**Comment by aforbis-stokes** [comment]
@suyashkumar I think the publish on the event is more useful for data analysis; however, I don't know how that affects the current software logic approach to collecting the bucket tip information. @mlp6 thoughts?

Also, I'm not sure of what the +/- is on data transmission. For example, I expect 200-400 tips / day. If we publish only events, that's 200-400 transmissions / day. When we publish tips every 2.5 mins, that is 576 transmissions / day. Seems like another benefit, but I may be missing something there/have flawed logic.

**Comment by mlp6** [comment]
What about if we publish a summary of the past 2.5 min only if there have been tips during that period.  We can store that information locally and then transmit something like the elapsed time since the last tip for each one.  That would limit the cell data, and put more of the heavy lifting on the packaging and parsing of data (which is totally fine).

**Comment by mlp6** [comment]
@aforbis-stokes what sort of precision do you need on the recorded time for each tip event?

**Comment by aforbis-stokes** [comment]
The current precision of tips / 2.5 min is acceptable...so I'm not totally pushing to make a change. If we do make a change, down to the minute is good. Any further is not necessary.

**Comment by mlp6** [comment]
Oh, that would make life easier - so just a number of tips since the last publish event would work?

**Comment by aforbis-stokes** [comment]
Correct

**Comment by suyashkumar** [comment]
@mlp6, @aforbis-stokes do we expect there to be multiple bucket tip events within a 2.5 minute window? If not, then your suggested approach would be similar to just publishing bucket tips events as soon as they happen--which gives us better time resolution for the same amount of data spent--unless I'm missing something? (though, I do realize we don't really need the better resolution, just curious)

Either approach is fine by me as it significantly cuts down on the number of repeat bucket tip transmissions that we currently have, but am slightly partial to just publishing the current bucket tip count when the increment occurs (if we don't have multiple tip events in a 2.5 min window).

**Comment by mlp6** [comment]
I think there can be...

**Comment by suyashkumar** [comment]
Cool! I can go ahead and get the relevant changes started, then. It may then also make sense to roll the bucket tips into the single `TEMPS` publish then to avoid the overhead of two publishes at the 2.5 minute mark...however, that'll require some significant changes to the server and also probably merits a refactor of the event naming so that's an optimization I'll create an issue for to be addressed in the future if we actually feel like shaving off even more data!

**Comment by mlp6** [comment]
Sounds good!

**Comment by suyashkumar** [comment]
Fantastic, will likely get to that this evening! :)

**Comment by aforbis-stokes** [comment]
I'm a little late to this discussion, but it seems you are already moving in the right direction. Yes, I do expect there will be occasions where there are multiple tips in the 2.5 minute window.

**Comment by suyashkumar** [comment]
@aforbis-stokes @mlp6 Another thing I remembered--if we are not sending bucket tip publishes when they occur and wish to maintain a global count on the device, it may prove burdensome to develop an efficient way to get the data you need on the server. Particularly if resets can occur in between. Have we considered storing bucket tip count in EEPROM if we really want to maintain a global count?

Or, instead of keeping a global count on the device, it'll be more useful on the server end (and save complications on the electron) for the electron to simply send the change in number of bucket since the last publish. I'll store this as a time series on the server in which form it'll be easy to query and ask the questions that Aaron alluded to before in this thread.

**Comment by mlp6** [comment]
I was hoping to have the server store all "global" count-type information for those reasons.  The one things to deal w/ is when the Particle goes offline for a while b/c of poor cell connectivity, and dealing w/ data that way... and if that is an extended time, then write data to EEPROM to survive a power blip.  These are on the radar for @DanielHull to address once he gets some of the hardware updates made.

**Comment by suyashkumar** [comment]
@mlp6 Awesome. Ultimately the best format for the server to hold data would be in a time series which serves well for plotting across various time bins. Calculating and storing such a time series would be easiest if the device does the following (from least burdensome to most):

1. Send a publish when a bucket tip occurs, for each bucket tip (200-400 transmissions/day)
2. Send the number of bucket tips since the last time reported at 2.5 min intervals (less transmissions if we have multiple bucket tips per 2.5 min interval, doesn't require any sort of global count on the device)
3.  The current solution of sending a global bucket tip count every 2.5 mins. It's hard to maintain resiliency on the device and it's not elegant to extract the data needed on the server.

I think 2 is likely the best option, so that we we don't have to worry about EEPROM and are resilient to bucket tip data within a 2.5 min window...

**Comment by suyashkumar** [comment]
Ah, I missed the part about the poor cell connectivity. In that case I still think number 2 is the way to go, we'd just publish the change in bucket tip count since the last _successful_ published. :)

**Comment by mlp6** [comment]
@suyashkumar is this still "open"?

**Comment by mlp6** [comment]
I think this is "done" for now, so going to close.
