### ISSUE TITLE
refactor probe temperature reading code

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#7]
Right now, in `loop()`, to following steps are performed serially:
1. Sample data on each probe
2. Average data on each probe
3. Convert each average to temperature (C)

The same exact operation is being performed for each probe, so will write a new `probeTempRead()` function that will do all of the "action" and then just loop for each probe in `loop()`.

**Comment by mlp6** [comment]
@aforbis-stokes Can you check that the code that I just pushed up to GitHub works for reading all of the temperature sensors still?  I refactored it a bunch, but wanted to make sure I didn't break any function.  I did verify that it will compile.  I will keep working on the other function in the mean time.

**Comment by aforbis-stokes** [comment]
Still works!

**Comment by mlp6** [comment]
That is amazing and almost never works when you blindly code!  I'm cleaning up more... need to run to another meeting in a few min, but will be back at it in a bit.  

Did you see how the code got condensed?  Is it still readable from your perspective?

**Comment by aforbis-stokes** [comment]
I see what you did, and there are some commands I am unfamiliar with, but I think I get it.
