### ISSUE TITLE
reduce dependence on cell connection during device boot

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#70]
cell connectivity appears to be an issue at some/all sites... might need to consider using `SYSTEM_THREAD(ENABLED)` (https://docs.particle.io/reference/firmware/electron/#system-thread) to create parallel application and system threads.  a larger concern is what happens to publish events in this setup, both in terms of:
1. offline (temporary) data storage
2. `loop()` execution

**Comment by mlp6** [comment]
@aforbis-stokes do you know how long a unit might remain on but offline?  asking from the perspective of how much data might need to be stored temporarily offline before it would get pushed when it does connect and how the data may persist if the unit loses power before it pushes the data.

**Comment by aforbis-stokes** [comment]
Hard to tell how long is it on/off. I have it plugged in while working all day, and it seems to off more than on when I periodically check. I would say off for at least 1-2 hours at a time.

I did find a cell signal booster in town today. I will try to install tomorrow to see what that does. I feel pretty optimistic.

**Comment by mlp6** [comment]
Okay... that isn't horrible.  And by "off", you mean lost cell connectivity, not turning off, correct?  I have software changes made, but I am a bit hesitant to push this change w/o testing a bit more.  I also want to see if there is newer system firmware that we can push to make it more cell robust.

**Comment by aforbis-stokes** [comment]
Yes, I meant "off" for cell connectivity. 

All of that sounds good. I am trying to go through a few troubleshooting steps from Particle tech support, but having issues getting Particle CLI to connect to the device over USB...
