### ISSUE TITLE
clean up old files in the repo

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#75]
we have accumulated a lot of outdated files... need to clean things up and tag

**Comment by aforbis-stokes** [comment]
Should I remove Arduino files? I don't image going back to those.
We can also remove the level_sensor portion of the code. We will no longer use that operation.

**Comment by mlp6** [comment]
ok - I'll do some cleanup based on that.  everything is stored in the git repo history, so it isn't actually "gone", but it keeps the working level populated only with relevant files.  I'll take care of this.
