### ISSUE TITLE
``millis()`` time rollover

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#76]
@aforbis-stokes do your devices in the field ever stay on for more than 49 days straight?  If so, then we need to take into account that the time variable that we are storing will rollover since we'll exceed the size of the data type ``millis()`` returns.

**Comment by aforbis-stokes** [comment]
@mlp6 they should stay on for more than 49 days straight if there is no failure or disconnection. If all was perfect (at least in current design), the Particle would never turn off or disconnect. We just have not been successful preventing those failures for that long. 
.

**Comment by mlp6** [comment]
okay, then we definitely need to actively account for a time rollover.

the issue is that a time is recorded as an `unsigned long int`, which means that the max value it can hold is `2**32 = 4294967296` ms, or ~49.7 days of elapsed time before running out of bit depth.

I think the best solution would be to keep track of elapsed time using a `float (32 bit)` in seconds, which would give us a lot more leeway in accumulated time, and still maintain the precision that we need, all in a convenient unit.

**Comment by mlp6** [comment]
I think that if we are streaming the data as diffs back to the web server, then we don't need to worry about this as much w/r to accumulated counts, etc..  Just need to check that none of our calculations will break if the reported time reset.
