### ISSUE TITLE
functional testing

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#8]
Latest code in the master branch is ready for testing.  As before, I wrote all of this blindly, but did verify compilation of the code.

Once the code is in a fully-functional form, we can explore the final phase of making it truly modular, but if we don't get to that milestone, you will still have a fully-functional version of code before your trip in a few weeks. 

You can create Issues for any bugs that you encounter and aren't sure how to fix; otherwise please edit away and let me know when the code is "ready".

**Comment by mlp6** [comment]
I am actively working on this a bit more, so hold off on testing this evening if you can and try in the morning.

**Comment by aforbis-stokes** [comment]
I've been trying to get the code to compile, but referencing the libraries is not working for me.

This error repeats for each library:
In file included from ADPL_mp.ino:4:
C:\Users\Aaron\Documents\Arduino\libraries\Pump/Pump.h:12: error: ISO C++ forbids initialization of member 'offTime'
C:\Users\Aaron\Documents\Arduino\libraries\Pump/Pump.h:12: error: making 'offTime' static
C:\Users\Aaron\Documents\Arduino\libraries\Pump/Pump.h:12: error: ISO C++ forbids in-class initialization of non-const static member 'offTime'

**Comment by mlp6** [comment]
Working on it... very strange since this will compile on my system just fine.

**Comment by mlp6** [comment]
Give it a try now with the latest version on the `master` branch.

**Comment by aforbis-stokes** [comment]
Have the program compiling/uploading/running on the Arduino.
The temp probes are working a little crazy. Here is the serial monitor output:

88.91, 43.48, nan, nan, 45.72, 0, 0
406.00
nan, 58.10, 54.07, 44.30, 62.26, 0, 0
410.00
nan, 82.67, 74.16, 58.76, 94.64, 0, 0
410.00
nan, nan, 129.28, 83.34, nan, 0, 0
409.00
47.69, nan, nan, -273.15, nan, 0, 0
410.00

**Comment by mlp6** [comment]
Were those temp numbers more stable yesterday?

**Comment by aforbis-stokes** [comment]
Yes, they were pretty constant. No "nan" outputs, all values staying around 22 or 23.

**Comment by mlp6** [comment]
Give it a try now...

**Comment by aforbis-stokes** [comment]
New output below. Previously 1 second between readings, now 5 seconds between.

nan, nan, nan, nan, nan, 0, 0
403.00
44.61, nan, nan, nan, 44.38, 0, 0
404.00
60.77, 56.99, 55.13, 55.74, 60.31, 0, 0
405.00
90.90, 80.54, 76.14, 77.55, 89.50, 0, 0
405.00
nan, 222.36, 143.30, 157.28, nan, 0, 0
404.00
nan, nan, nan, nan, nan, 0, 0
403.00

**Comment by mlp6** [comment]
I love making things worse.  :)  Okay... I'll look at this a bit more.  What would be your preferred time b/c readings?

**Comment by mlp6** [comment]
Give it a try now... I realize that I never set the samples and average private members to 0 for each new `read()` call, which was probably causing all sorts of issues.

**Comment by aforbis-stokes** [comment]
I'm ok with 5 second between readings. I'm storing readings on a 4GB SD card for a week, which I believe has capacity to store these readings every second, but that amount of data is not necessary.

Timing back to 1 second between readings, but output not giving any real numbers:
nan, nan, nan, nan, nan, 0, 0
415.00
nan, nan, nan, nan, nan, 0, 0
416.00
nan, nan, nan, nan, nan, 0, 0
419.00

**Comment by mlp6** [comment]
Can you test w/ the latest version... I have put some additional serial print statements in there to help me first out what is not happy.

**Comment by aforbis-stokes** [comment]
Getting a compiling error. Did you only edit TempProbe.CPP ? The new folder does not come up with the .h file, but I have left the most recent in the library.

C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp: In member function 'void TempProbe::read()':
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:27:5: error: expected ';' before 'timeRead'
     timeRead = millis();
     ^
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:32:5: error: expected ';' before '_sampleMean'
     _sampleMean = 1023. / _sampleMean - 1.;
     ^
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:34:5: error: expected ';' before '_sampleMean'
     _sampleMean = _SERIESRESISTOR / _sampleMean;
     ^
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:38:5: error: expected ';' before 'temp'
     temp = _sampleMean / _THERMISTORNOMINAL;        // (R/Ro)
     ^
Error compiling.

**Comment by mlp6** [comment]
Whoops, there was a syntax error that I introduced.  Give it a try now.

**Comment by aforbis-stokes** [comment]
New output (repeats each reading):
-11425-114.25-9.95-1004.62-10889-108.89-10.39-962.02-10636-106.36-10.62-941.77-10636-106.36-10.62-941.77-11436-114.36-9.95-1005.49nan, nan, nan, nan, nan, 0, 0
418.00

**Comment by mlp6** [comment]
I have reverted some of the logic I consolidated... give it a try now.  (fingers crossed)

**Comment by aforbis-stokes** [comment]
New output:
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
404.00
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
404.00
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
440.00
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
451.00
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
444.00

**Comment by mlp6** [comment]
Okay - another debugging copy in master - can you send me that serial terminal output?

**Comment by aforbis-stokes** [comment]
Error in compiling:

C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp: In member function 'void TempProbe::read()':
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:24:28: error: call of overloaded 'println(int [10])' is ambiguous
     Serial.println(_samples);
                            ^
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:24:28: note: candidates are:
In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Stream.h:26:0,
                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/HardwareSerial.h:29,
                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:223,
                 from C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:5:
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:73:12: note: size_t Print::println(char) <near match>
     size_t println(char);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:73:12: note:   no known conversion for argument 1 from 'int [10]' to 'char'
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:74:12: note: size_t Print::println(unsigned char, int) <near match>
     size_t println(unsigned char, int = DEC);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:74:12: note:   no known conversion for argument 1 from 'int [10]' to 'unsigned char'
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:75:12: note: size_t Print::println(int, int) <near match>
     size_t println(int, int = DEC);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:75:12: note:   no known conversion for argument 1 from 'int [10]' to 'int'
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:76:12: note: size_t Print::println(unsigned int, int) <near match>
     size_t println(unsigned int, int = DEC);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:76:12: note:   no known conversion for argument 1 from 'int [10]' to 'unsigned int'
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:77:12: note: size_t Print::println(long int, int) <near match>
     size_t println(long, int = DEC);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:77:12: note:   no known conversion for argument 1 from 'int [10]' to 'long int'
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:78:12: note: size_t Print::println(long unsigned int, int) <near match>
     size_t println(unsigned long, int = DEC);
            ^
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Print.h:78:12: note:   no known conversion for argument 1 from 'int [10]' to 'long unsigned int'
Error compiling.

**Comment by mlp6** [comment]
Should be fixed; give it a try now.  I'm headed out for a bit, but hopefully will figure out based on your output what is going wrong here.  This must be a variable-type error or something like that.

**Comment by aforbis-stokes** [comment]
New output (each reading gives an output like this): 

1081
1080
1081
1080
1082
1082
1081
1081
1081
1080
10809.00
1080.90
-186683.78

**Comment by mlp6** [comment]
Well, that sheds some light on the problem... that streaming value (first 10) should never exceed 1023.  Try the latest version.

**Comment by aforbis-stokes** [comment]
Same kind of output. I noticed there is a Arduino.h command. I do not think I have a Arduino file in the library, but I'm guessing that is a standard command for all Arduinos.

542
542
542
542
542
542
542
542
542
542
11268.19

**Comment by mlp6** [comment]
What temperature did this output yield?

**Comment by aforbis-stokes** [comment]
Sorry, missed that line in copy/paste.

0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
452.00

**Comment by aforbis-stokes** [comment]
I ran the consolidated temp probe from yesterday, again. Here is that output for reference:

22.36, 21.82, 21.56, 21.56, 22.34, 471.00
0, 0, 1
22.36, 21.82, 21.56, 21.56, 22.34, 469.00
1, 0, 1
22.37, 21.82, 21.56, 21.56, 22.34, 466.00
1, 0, 1

**Comment by mlp6** [comment]
Good news is that 542 and 11268 are correct in the raw output you sent (corresponds to the temps you send from the old code).  Try the version I just uploaded that will print output at each step of the deg C conversion.  Should be able to figure this out soon!!

**Comment by aforbis-stokes** [comment]
Ran into another compile error. I tried finding that missing ")" myself, but everything I saw was closed.

Build options changed, rebuilding all
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp: In member function 'void TempProbe::read()':
C:\Users\Aaron\Documents\Arduino\libraries\ADPLmaster\TempProbe.cpp:41:5: error: expected ')' before 'Serial'
     Serial.println(temp);
     ^
Error compiling.

**Comment by mlp6** [comment]
fix pushed up; try it now!

**Comment by aforbis-stokes** [comment]
Sorry, needed to have unscheduled meeting with my advisor. New output:

1.18
0.16
0.00
0.00
294.53
21.38
553
553
553
553
553
553
553
553
553
553
Thermistor resistance (Ohm):11765.96
1.18
0.16
0.00
0.00
294.53
21.38
544
544
544
544
543
544
544
544
544
544
Thermistor resistance (Ohm):11352.54
1.14
0.13
0.00
0.00
295.32
22.17

**Comment by mlp6** [comment]
Great... the temps look correct... so why are the other ones being displayed wrong?!

**Comment by aforbis-stokes** [comment]
Running through this again today and noticed I missed something last time. The other prints are being displayed, I missed that line as I was scrolling through the output. However, on that line the temps are still being displayed as 0.0.

548
548
547
548
548
548
548
548
548
548
Thermistor resistance (Ohm):11532.31
1.15
0.14
0.00
0.00
294.98
21.83
558
558
558
558
558
558
558
558
558
558
Thermistor resistance (Ohm):12000.00
1.20
0.18
0.00
0.00
294.10
20.95
560
560
560
560
560
560
560
560
560
560
Thermistor resistance (Ohm):12095.03
1.21
0.19
0.00
0.00
293.93
20.78
561
561
561
561
561
561
561
561
561
561
Thermistor resistance (Ohm):12142.86
1.21
0.19
0.00
0.00
293.84
20.69
549
549
549
549
549
549
549
549
549
549
Thermistor resistance (Ohm):11582.28
1.16
0.15
0.00
0.00
294.88
21.73
0.00, 0.00, 0.00, 0.00, 0.00, 1, 0
407.00

**Comment by mlp6** [comment]
So, all of the temps are correct (the 2?.?? numbers that precede the 5?? numbers), but the temp is just being read / displayed incorrectly from `loop()`.   Try the latest version now to see some consolidated debug statements.

**Comment by aforbis-stokes** [comment]
New output:
Thermistor Temperature (deg C):21.55
Thermistor Temp in loop: 0.00
Thermistor Temperature (deg C):21.99
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.67
Thermistor Temperature (deg C):21.51
Thermistor Temperature (deg C):21.55
Thermistor Temp in loop: 0.00
Thermistor Temperature (deg C):22.01
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.65
Thermistor Temperature (deg C):21.50

**Comment by aforbis-stokes** [comment]
And, what you are saying is correct. All the readings looked good, just something funny in the output.

**Comment by mlp6** [comment]
Okay - this should be a "simple" variable reference fix.  I'll try to debug just on my end w/o you having to test everything.  Does the rest of the code work?

**Comment by mlp6** [comment]
Can you try the latest version I pushed (still debugging, but I'm not getting this error on my local compile).

**Comment by aforbis-stokes** [comment]
Newest output:
Thermistor Read Temperature at:6487
Thermistor Temperature (deg C):21.12
Thermistor Temp in loop: 0.00
Thermistor Read Temperature at: 6487
Thermistor Read Temperature at:6779
Thermistor Temperature (deg C):21.73
Thermistor Read Temperature at:7002
Thermistor Temperature (deg C):28.80
Thermistor Read Temperature at:7224
Thermistor Temperature (deg C):21.72
Thermistor Read Temperature at:7445
Thermistor Temperature (deg C):21.83

**Comment by mlp6** [comment]
Well, that is infuriating... the timeRead variable is being correctly printed (6487) within the object and in loop(), but temp isn't.  How long are you at work this afternoon to iterate on this?

**Comment by aforbis-stokes** [comment]
I can stay another hour.

I am checking other parts out, and a few other things are strange. The valve is staying open (reading 1 in serial monitor and also measuring voltage) even when the temperature goes from below 25 to above 28, and doesn't change when it goes back down.

The relay for the ignitor was previously going on/off every 5 seconds, but now is staying on.

Have not gotten to do a good test on level sensor turning on the pump (other than getting the reading).

Not sure if that is something easier to debug in person.

**Comment by mlp6** [comment]
Can you try the latest master version...

**Comment by mlp6** [comment]
The valve parts won't work now b/c the temps are coming out as 0 all the time in the logical tests, so that doesn't surprise me.

**Comment by aforbis-stokes** [comment]
New output:
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):26.82
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.91
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):26.82
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.90
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):26.87
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.90
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):26.91
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.90
Thermistor Temperature (deg C):21.12
Thermistor Temp in loop: 21.12
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):26.91
Thermistor Temperature (deg C):21.73
Thermistor Temperature (deg C):21.90
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13

**Comment by mlp6** [comment]
WOOHOO!!  That was a typo error I had buried in the code that I found... see if the valves will work now.  And lets make a list of what ever else is wacko.

**Comment by aforbis-stokes** [comment]
The Arduino output (actual signal & serial monitor) to the the valve is perfect. No signal when above 28C, once it drops below 25 there is a signal until back about 28.
The ignitor signal is a little off. It only operates when the valve is open, but the timer is more like on for 5 seconds, off 1 second, repeat.
I might need to move the set up to my lab to test the level sensor better. Without a good amount of water, it's hard to tell, and I'm nervous to do that in this electronics lab.

**Comment by mlp6** [comment]
Let me check the ignitor now... if we have that working, then I think you can relocate to your lab.

**Comment by mlp6** [comment]
Try now... check for more correct ignitor function, and some new serial output you can send me if we need to debug more.

**Comment by aforbis-stokes** [comment]
Still the same on ignitor
1, 0
330.00
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.81
Thermistor Temperature (deg C):21.74
Thermistor Temperature (deg C):21.57
Thermistor Temperature (deg C):22.16
1, 0
333.00
Thermistor Temperature (deg C):21.13
Thermistor Temp in loop: 21.13
Thermistor Temperature (deg C):21.81
Thermistor Temperature (deg C):21.70
Thermistor Temperature (deg C):21.56
Thermistor Temperature (deg C):22.16

**Comment by mlp6** [comment]
That doesn't look like the latest code is running.  I just pushed up even more verbose code to try.

**Comment by aforbis-stokes** [comment]
You're right, forgot to re-open the .ino

Ignitor last fired: 6164
Ignitor last fired: 12328
Ignitor last fired: 18493
Ignitor last fired: 24658
Ignitor last fired: 30823
Ignitor last fired: 36988

**Comment by mlp6** [comment]
That still looks like an old version...

**Comment by aforbis-stokes** [comment]
in class time: 6164
TOO LOW - Ignitor last fired: 6164
in class time: 12329
TOO LOW - Ignitor last fired: 12329
in class time: 18495
TOO LOW - Ignitor last fired: 18495

**Comment by mlp6** [comment]
Right now it is firing all of the time b/c it is falling below the incineration low temp threshold (25 deg C), as specified on line 82.  I didn't have a test if the valve was open or closed there, so it was just refiring each time through.  I have added a test for valve status now.  See if that makes a difference.

**Comment by aforbis-stokes** [comment]
Ok, I think it's good now. On for 5 seconds, been at least a couple minutes off.

**Comment by mlp6** [comment]
Great... I would move the setup so you can test water level, and then maybe be able to modulate temperature to test that too.  Keep me posted... I'll be online this weekend at times.

**Comment by aforbis-stokes** [comment]
Ok, I should probably head home for now and will do that in the morning. Will update you then.

**Comment by aforbis-stokes** [comment]
I think this is all good! Pump and ignitor timers both working correctly, not conflicting. Signals coming from the Arduino at the right times and under the correct situations.
Removing the comment out on the serial print gives the correct display for all readings.

**Comment by mlp6** [comment]
Great!  Do you need any additional functionality now that we have it in a good place?  I didn't touch the SD card parts, but those can also be significantly consolidated.  Thoughts?

**Comment by aforbis-stokes** [comment]
I now have a hardware issue, though. I accidentally ran the relays with 12V instead of 5V. 2 of 3 three I think are fried. Looking at the setup and specs, I think I should replace all of them with 12VDC relays. 12VDC is an acceptable input for all components (including Arduino) except for the ignitor (1.5V, using a AA battery). I'm going to swing by Radioshack on my way home to see if they have some.

**Comment by aforbis-stokes** [comment]
I need to convert the level analog reading into a height. I'm trying to follow the example of the thermistor conversion, but I think the level sensor operates a little differently.

**Comment by mlp6** [comment]
Is the spec sheet in `docs/`?  If so, then I'll take a peek at that.  I'll start a new issue for this.

**Comment by aforbis-stokes** [comment]
I still don't have GitHub totally figured out. Attached is an updated
document. P3 has a consolidated spec sheet.
