### ISSUE TITLE
upgrade firmware to v0.6.0

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#82]
necessary to:
1. implement ``Logging`` class
2. fix some bugs that could rear their head and affect us (though haven't to date)

**Comment by aforbis-stokes** [comment]
How is the firmware updated remotely? The Particle docs make it sound like the device needs to be switched to DFU mode first. Is there a command window call, like "particle flash [device] firmware0.6.0" ? Or can it be changed using Particle Build (using the drop-down menu showing version)?

**Comment by mlp6** [comment]
We can do it from the CLI using the example syntax you showed.  Typically we have to download two files since the firmware is too large to flash in one step.  I have flashed several of the device firmwares before, but it is a bit of a "fingers crossed" moment.

**Comment by mlp6** [comment]
I usually test run on a local Duke unit first to stress test it a bit before deploying remotely.

**Comment by aforbis-stokes** [comment]
Ok. The Duke version ADPLDuke0785 version is plugged in now. Kenya devices ADPL_KE_north and ADPLKenyaCentral9822 should both be powered on at Patrick's (field guy) home. He is away from home for another hour or so.

**Comment by aforbis-stokes** [comment]
Patrick now home and can reset if needed. He has two fresh Electrons set up (found older Electrons were damaged). The Electrons needing the firmware upgrade and software flash are "ADPL_KE_north" and "ADPL_KE_central" (forget about ADPLKenyaCentral9822)
