### ISSUE TITLE
mothball the level sensor?

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#88]
is this true?  if so, then what modulates the pump activity?

**Comment by aforbis-stokes** [comment]
Correct. We kept having hardware issues with the level sensor and redesign the collection tank to have a manual overflow so that the sensor was no longer necessary. The pump purely runs on the timer.

**Comment by mlp6** [comment]
And that pump timer is independent of the MCU, correct?  i.e., can I disable all calls to running the pump in the code?

**Comment by aforbis-stokes** [comment]
The timer does run off of the MCU. I forgot how (sorry, I should have logged this), but I have the program running with the code still telling the pump to turn on and off. It may be that when the sensor is not connected, the reading becomes such that the program thinks the level is in the intermediary region that causes the pump to run on the timer. I can see this in the lab unit as the pump pin is on D7, the LED pin, and it turns on and off according to the program's timer

So, this code section still applies:
currentTime = millis();
        if (!pump.pumping && (currentTime - pump.offTime) > KEEP_PUMP_OFF_TIME) {
            pump.turnOn();
        }
        else if (pump.pumping) {
            if ((currentTime - pump.onTime) > KEEP_PUMP_ON_TIME) {
                pump.turnOff();

**Comment by mlp6** [comment]
Got it; I'll clean up the code to remove the level sensor hooks, but I'll preserve all of the pump timing.

**Comment by mlp6** [comment]
Commit f2ecb62e23ee7d3b5b6d6d1da318f84880684cc1 removed the level pin map, but there is dependent code that still exists, so master will no longer compile.  Need to fix this ASAP.
