### ISSUE TITLE
Unparseable Messages

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#93]
@mlp6 reported the following. I'll add in classic error handling logic to mitigate and catch this in the future. 

> Web server was down; inspecting the screen session had this error message:
> 
> ```
> New Message
> /home/bitnami/ADPL/software/logging/handle-device.js:26
>                         realData.temp = realData.data.split(",")[d].split(":")[1].replace(/\s+/g, '');
>                                                                                  ^
> 
> TypeError: Cannot read property 'replace' of undefined
>     at EventSource.<anonymous> (/home/bitnami/ADPL/software/logging/handle-device.js:26:61)
>     at emitOne (events.js:77:13)
>     at EventSource.emit (events.js:169:7)
>     at _emit (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:181:17)
>     at parseEventStreamLine (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:196:9)
>     at IncomingMessage.<anonymous> (/home/bitnami/ADPL/software/logging/node_modules/eventsource/lib/eventsource.js:159:11)
>     at emitOne (events.js:77:13)
>     at IncomingMessage.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at IncomingMessage.Readable.push (_stream_readable.js:111:10)
>     at HTTPParser.parserOnBody (_http_common.js:127:22)
>     at TLSSocket.socketOnData (_http_client.js:322:20)
>     at emitOne (events.js:77:13)
>     at TLSSocket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at TLSSocket.Readable.push (_stream_readable.js:111:10)
> ```
> Manually-restarted the web server... will keep an eye on this.

**Comment by mlp6** [comment]
👍

**Comment by suyashkumar** [comment]
Looking at this, might be able to rewrite this logic to the new byte-saving single publishes :)

**Comment by mlp6** [comment]
Stellar... I effectively use your changes as learning opportunities for myself on this end of things.

**Comment by suyashkumar** [comment]
:D Of course! I hadn't even realized the byte-saving fix was implemented on the firmware side (which makes so much sense)! I'll add you as a reviewer on the pull requests

**Comment by suyashkumar** [comment]
At some point we should add in unit tests here if we plan on keeping the NodeJS code base! It'd be great to get this project to 100% unit test coverage as we increase it's complexity and global rollout :)
