### ISSUE TITLE
Absolute power usage 

### ISSUE THREAD

**Issue by oo22** [mlp6/ADPL#95]
Quantifying absolute power usage by the device during a 24 hour period

**Comment by oo22** [comment]
Did you have any ideas of how you wanted to approach this?

**Comment by oo22** [comment]
http://www.ti.com/lit/wp/slay023/slay023.pdf 
very helpful in calculating the system's use of power.

**Comment by aforbis-stokes** [comment]
I installed a 2Ohm resistor on the anode side of power supply line. I am using a Vernier Instruments differential voltage meter and data logger to measure voltage drop across the resistor. Knowing power supply voltage and resistance, I can calculate current and then power.

**Comment by oo22** [comment]
What is the data logger? 
(1) I think the power usage may not be consistent the entire time because the power usage will vary based on the tasks that the MCU is doing (taking in data, resting etc) at different times. To not make it too complicated, from my understanding, we can generalize and say that there are two main events ( for example 1 event when the MCU is not turning on the ignitor and 1 event when the MCU is turning on the ignitor). Each of those events will take a certain amount of time and you can measure the voltage during those events.  *this may not matter..I guess we shall see*
(2)  I would suggest using an oscilloscope so that you can record the voltage waveform during an event. And then calculate the average value of the voltage waveform (Vrms). P = V^2/R
(3)  We may not get a perfect waveform which we can use to calculate the average voltage during an event. We just have to test and see. 

These are my thoughts.

**Comment by mlp6** [comment]
I think that for getting an average usage over a long period of time, then Aaron's approach should work well, especially if you trigger action events along the way that contribute to total power consumption.

If you care about transient power draw, then I would look into Siji's approach for a discrete device connected to the entire system.
