### ISSUE TITLE
PCB Board Design 

### ISSUE THREAD

**Issue by oo22** [mlp6/ADPL#98]
@a.forbis.stokes : how big do you want the PCB board to be?  i was thinking about just getting the relays on another board just keep the grounds physically separate . Is that ok?

**Comment by aforbis-stokes** [comment]
The board can be whatever size is necessary. My hope for the custom board is a more clean, organized layout. I would assume that would reduce the total footprint of my existing circuit board + relay board. As long as the new board does not increase the overall size, I am ok.

**Comment by oo22** [comment]
would you like the headers that you used for the relay board on the circuit board or just regular headers?

**Comment by oo22** [comment]
do you want a separate circuit board for the ignitor button circuit?

**Comment by aforbis-stokes** [comment]
No, I'll continue to mount the momentary push-button on the enclosure box containing the igniter. I'll use the twist-cap connectors to connect the wires.

**Comment by oo22** [comment]
ok. where is the TVS diode going to be then?

**Comment by aforbis-stokes** [comment]
I will connect that with the twist-caps as well. I think a custom board just to solder a few wires & TVS together would be overkill. If it is quick and super cheap to make one for that, it wouldn't hurt, but I don't see a good reason to spend >$10 on a board for that purpose.

**Comment by mlp6** [comment]
You can do those small, one-off boards just as soldered perf-board, not an etched PCB.

**Comment by mlp6** [comment]
I haven't seen any commits w/ the actual control board PCB; are those coming?

**Comment by oo22** [comment]
yes it is. I'm making some components PCB editor.

**Comment by mlp6** [comment]
also, @oo22 you committed a new version of a file I had deleted b/c it was outdated

`ADPL.SchDoc` was deleted; `ADPL Wiring Diagram.SchDoc` was the latest one.  why was the old one ressurected?

**Comment by oo22** [comment]
mhmm My latest one I have is called ADPL.SchDoc. ADPL wiring Diagram is the old one

**Comment by oo22** [comment]
ADPL wiring diagram and ADPL_Board should be deleted because they are old

**Comment by oo22** [comment]
going to clean that up right now cause the file that I was just working got deleted cause I was opening too many files with the same name.

**Comment by oo22** [comment]
@aforbis-stokes some of the boards will have 3 headers for the relays to connect to the three different relays (ignitor, pump, valve) and some will only have 2 headers to connect to 2 different relays (ignitor and pump), correct? I just want to double check

**Comment by aforbis-stokes** [comment]
Mostly correct. One board has 3 relays (ignitor, pump, valve)  and other has 2 (ignitor and Valve). For reference, though, the two relay version is for the majority of systems and likely all future systems. The project in India is the only one with the pump, and it is a special case scenario that likely will not be repeated. I would focus on the 2 relay version and then make it so that adding an additional relay would not be difficult for this (or any other) special case.
